### ISSUE TITLE
OSM Users

### ISSUE THREAD

**Issue by cchristelis** [kartoza/osm-reporter#115]
# Problem

Our site needs to know who is using the application.

# Proposed Solution 

Use the OSM user identity here.

**Comment by dimasciput** [comment]
@cchristelis then we need a database, should we use sql for this? We can use try library http://flask-sqlalchemy.pocoo.org/2.1/. What do you think?

**Comment by dimasciput** [comment]
We can do authentication with this library https://github.com/osmlab/osm-auth using oath. We will need to register application first in openstreetmap to get consumer key and secret key.

**Comment by meomancer** [comment]
And also, application in here should be already in staging or production server, because openstreetmap need url for returning auth_token. 
We could develop using localhost, that openstreetmap allows it.
