### ISSUE TITLE
OverPass API 0.7 available

### ISSUE THREAD

**Issue by yohanboniface** [kartoza/osm-reporter#12]
From the ML:

> A new version of Overpass API
> http://wiki.openstreetmap.org/wiki/Overpass_API
> is available. Please read
> http://wiki.openstreetmap.org/wiki/Overpass_API/versions#Overpass_API_v0.7.1
> for details.

Maybe is sane to wait a little before using it, to let hurry people bêtatest it ;)

**Comment by timlinux** [comment]
I'm going to close this out - @Gustry already added support for fetching only features of interest now.
