### ISSUE TITLE
We need to support localised QGIS qml downloads

### ISSUE THREAD

**Issue by timlinux** [kartoza/osm-reporter#22]
# Problem

When downloading roads or buildings from InaSAFE we should be able to pass a

```
&lang=id
```

flag on the url and then send the user back a version of the .qml (for roads and buildings) where the legend has been localised to Bahasa Indonesia.

**Note:** the flag should be optional, defaulting to ``en`` if not present.

# Proposed solution

- [ ] Add a new ``qml`` each for roads and buildings with ``id-`` suffix.
- [ ] Let url handler check for presence of ``lang`` flag then look for an appropriately prefixed file
- [ ] Add the localised qml to the zip if it is present, otherwise fall back to the default english on.
- [ ] Update InaSAFE to pass the locale flag in the url when making a download request.

# Expected outcome

Users should be able to get a nice downloaded layer with legend items matching their local.

**Comment by Gustry** [comment]
The name of the layers are provided also by the keyword file in the title, not only the QML.
I think we should also have xxxx-en.keywords.
