### ISSUE TITLE
Ship good keywords according to the plugin version.

### ISSUE THREAD

**Issue by Gustry** [kartoza/osm-reporter#62]
Inasafe provides its version in the URL : inasafe_version
osm-reporter should ship the good keywords file according to the version number.

Actually, osm-reporter only provides .keywords every time.
Does osm-reporter need to process like this ?
version < 3.2 : only the actual .keywords
version >= 3.2 : only .xml

If no inasafe_version is detected, we consider that the user is running <3.2, so we provide the .keywords.

CC : @timlinux

**Comment by timlinux** [comment]
I think we need to have logic in place that :

* no inasafe_version supplied - provide 'legacy keywords and xml' (what are currently offered)
* inasafe_version >= 3.2 provide only xml keywords versioned at 3.2
* In future we may need to add further rules if we change the standard format (though I expect that we should handle this type of migration in the InaSAFE application layer post 3.2)

**Comment by Gustry** [comment]
> no inasafe_version supplied - provide 'legacy keywords and xml' (what are currently offered)
Ok, legacy keywords are not versioned. But what about xml ? the latest one ?

**Comment by Gustry** [comment]
See https://github.com/kartoza/osm-reporter/pull/63
