### ISSUE TITLE
Add more user inputs to report, for example date range

### ISSUE THREAD

**Issue by TylerRadford** [kartoza/osm-reporter#70]
Date range would help when an area was mapped in one year and then updated in another year by a different team of people. It would allow reporting only on the current "round" of data collection.

**Comment by Gustry** [comment]
For your information, I saw this website last week : http://overpass-api.de/achavi/
We can select a date range to see only modified/created objects in the bbox.

**Comment by bgirardot** [comment]
I agree a date range would be useful for the tool as well.

**Comment by Gustry** [comment]
We can set a date in the overpass query : http://overpass-turbo.eu/s/nUQ

**Comment by Gustry** [comment]
This feature has been deployed on our staging server: 
http://staging.osm.kartoza.com
You can try there.

It will land on osm.inasafe.org soon.
