### ISSUE TITLE
Translate metadata and qml to Bahasa Indonesia

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/osm-reporter#84]
Please make it true :)

**Comment by Gustry** [comment]
In case of you forgot this ticket, I wrote some documentation :) 
https://github.com/kartoza/osm-reporter/blob/develop/reporter/resources/shapefile/translation.readme

**Comment by ismailsunni** [comment]
Hi @Gustry 
I just curious when I want to start translate the metadata and qml. Why don't we use transifex like in InaSAFE? It will be hard to maintain each file for each language for each version and for each layer (building, idp, road, etc)

My idea, create a template for each version, then generate it on the fly (or generate it once when we run a management command).
Moreover, perhaps we can share the terminology between InaSAFE repo and OSM-reporter repo in transifex.
Or more fancy, perhaps we can add something like git-hook in transifex, to update the translation and update the translation whenever new translation made. *I am getting too far, ahaha

What do you think? I am happy to help, for sure :)

Anyway, I have made a PR for this see #92

**Comment by timlinux** [comment]
Can we close this @ismailsunni ?

**Comment by Gustry** [comment]
Yes, we can
